routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/artisan', 'ArtisanController@artisan')->name('artisan');

Auth::routes();
Route::get('/', 'HomeController@index')->name('index');
Route::prefix('/blog')->name('blog.')->group(function() {
    Route::get('/', 'HomeController@blog')->name('blog');
    Route::get('/{id}', 'HomeController@showBlog')->name('show');
});
Route::middleware(['auth'])->group(function() {
    Route::prefix('/admin')->name('admin.')->group(function() {
        Route::get('/', 'BlogController@index')->name('index');
        Route::get('/new', 'BlogController@create')->name('create');
        Route::post('/new', 'BlogController@store')->name('store');
        Route::get('/{id}', 'BlogController@edit')->name('edit');
        Route::post('/{id}', 'BlogController@update')->name('update');
        Route::get('/{id}/destroy', 'BlogController@destroy')->name('destroy');
    });
});

Route::get('/articles', 'BlogController@getArticlets')->name('getArticlets');
Route::get('/article/{id}', 'BlogController@getArticle')->name('getArticle');

app/Blog.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    public function showCategory(){
        switch ($this->category) {
            case '1':
                return 'Violencia de Género';
                break;
            case '2':
                return 'Delitos Contra la Propiedad';
                break;
            case '3':
                return 'Delitos Informáticos';
                break;
            case '4':
                return 'Derecho Penal Corporativo';
                break;
            default:
                return 'sin categoría';
                break;
        }
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ArtisanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Artisan;

class ArtisanController extends Controller
{
    public function artisan(Request $request)
    {
        // EJ /artisan?command=migrate:fresh
        Artisan::call($request->command);
        dd(Artisan::output());
    }
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\Blog;
use Illuminate\Http\Request;
use Validator;

class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $blogs = Blog::all();
        return view('admin.index')->with('blogs', $blogs);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.new');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request);
        Validator::make($request->all(), [
            'title' => 'required|max:255',
            'category' => 'required|integer',
            'img' => 'required|image|mimes:jpeg,png,jpg|max:2048',
            'info' => 'required',
        ])->validate();

        $blog = new Blog;
        $blog->title = $request->title;
        $blog->category = $request->category;
        $blog->info = $request->info;
        $blog->article = $request->article;
        $blog->squillContents = $request->squillContent;
        $blog->img = "";
        $blog->save();
        if($request->hasFile('img')){
            $img = $request->file('img');
            $filename = $blog->id . '-' . 'img' . '-' . time() . '.' . $img->getClientOriginalExtension();
            $blog->img = $filename;
            $img->move(public_path('/storage/blog'), $filename);
        }
        $blog->save();
        return redirect('admin');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function show(Blog $blog)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $blog = Blog::find($id);
        return view('admin.edit')->with('blog', $blog);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // dd($request->request);
        Validator::make($request->all(), [
            'title' => 'required|max:255',
            'category' => 'required|integer',
            'img' => 'image|mimes:jpeg,png,jpg|max:2048',
            'info' => 'required',
        ])->validate();

        $blog = Blog::find($id);
        $blog->title = $request->title;
        $blog->category = $request->category;
        $blog->info = $request->info;
        $blog->article = $request->article;
        $blog->squillContents = $request->squillContent;
        $blog->img = "default.png";
        $blog->save();
        if($request->hasFile('img')){
            $img = $request->file('img');
            $filename = $blog->id . '-' . 'img' . '-' . time() . '.' . $img->getClientOriginalExtension();
            $blog->img = $filename;
            $img->move(public_path('/storage/blog'), $filename);
        }
        $blog->save();
        return redirect('admin');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $blog = Blog::find($id);
        $blog->delete();
        return redirect('admin');
    }

    public function getArticlets()
    {
        $blogs = Blog::all();
        return response()->json($blogs, 200, []);
    }

    public function getArticle($id)
    {
        $blog = Blog::find($id);
        return response()->json($blog, 200, []);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Blog;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $blogs = Blog::orderBy('created_at', 'desc')->take(3)->get();
        return view('welcome')->with('blogs', $blogs);
    }

    public function blog()
    {
        $blogs = Blog::paginate(10);
        return view('blog.index')->with('blogs', $blogs);
    }

    public function showBlog($id)
    {
        $blogs = Blog::orderBy('created_at', 'desc')->take(3)->get();
        $article = Blog::find($id);
        return view('blog.show')->with('article', $article)->with('blogs', $blogs);
    }
}

resources/views/admin/edit.blade.php
@extends('admin/layouts/layout')
@section('content')

<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Editar Artículo "{{$blog->title}}"</h1>
    </div>
    <section class="row">
        <div class="col-md-12">
            <form method="POST" action="" id="articleForm" enctype="multipart/form-data">
                <input type="text" hidden id="aritcle_id" value="{{$blog->id}}">
                @csrf
                <div class="form-group col-md-6">
                    <label for="title">Título:*</label>
                    <input @error('title') is-invalid @enderror required type="text" class="form-control" id="title" name="title" value="{{$blog->title}}">
                </div>
                <div class="form-group col-md-6">
                    <label for="category">Categoría:*</label>
                    <select @error('category') is-invalid @enderror required class="form-control" id="category" name="category">
                        <option selected disabled>Seleccionar</option>
                        <option @if($blog->category == 1) selected="selected" @endif value="1">Violencia de Género</option>
                        <option @if($blog->category == 2) selected="selected" @endif value="2">Delitos contra la propiedad</option>
                        <option @if($blog->category == 3) selected="selected" @endif value="3">Delitos informáticos</option>
                        <option @if($blog->category == 4) selected="selected" @endif value="4">Derecho Penal Corporativo</option>
                    </select>
                </div>
                <div class="form-group col-md-10">
                    <label for="img">Imagen:* (Tamaño recomendado 600x600)</label>
                    <input @error('img') is-invalid @enderror type="file" id="img" name="img">
                </div>
                <img src="/storage/blog/{{$blog->img}}" style="max-width:600px; max-height:600px;" alt="{{$blog->title}}">
                <div class="form-group col-md-10">
                    <label for="info">Texto:*</label>
                    <div id="editor" style="height: 450px; margin-bottom: 20px"></div>

                    {{-- <textarea @error('info') is-invalid @enderror required class="form-control" id="info" name="info" rows="16">{{$blog->info}}</textarea> --}}
                </div>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif  
                <input type="text" hidden name="info" id="info">
                <input type="text" hidden name="article" id="article">
                <input type="text" hidden name="squillContent" id="squillContent">
                <button class="btn btn-primary" type="submit" style="width:220px; margin-bottom:20px">Cargar</button>
            </form>
        </div>
    </section>
</main>
   
<script src="{{ asset('js/admin/edit-article.js') }}" defer></script>
@endsection

resources/views/admin/index.blade.php
@extends('admin/layouts/layout')
@section('content')

<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Artículos</h1>
    </div>
    <section class="row">
        <div class="col-md-12">
            <table id="blog-table" class="display" style="width:100%">
                <thead>
                    <tr>
                        <th>Título</th>
                        <th>Categoría</th>
                        <th>Contenido</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {{-- @foreach ($blogs as $blog)
                        <tr>
                            <td>{{$blog->title}}</td>
                            <td>{{$blog->showCategory()}}</td>
                            <td>{{$blog->info}}</td>
                            <td><a href="{{route('admin.edit', $blog->id)}}">Editar</a> / <a href="{{route('admin.destroy', $blog->id)}}">Eliminar</a></td>
                        </tr>
                    @endforeach --}}
                </tbody>
                <tfoot>
                    <tr>
                        <th>Título</th>
                        <th>Categoría</th>
                        <th>Contenido</th>
                        <th>Acciones</th>
                   </tr>
                </tfoot>
            </table>
        </div>
    </section>
</main>
@endsection

resources/views/admin/layouts/layout.blade.php
<!doctype html>
<html lang="es">
    <head>    
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="We Management">
        <meta name="generator" content="Jekyll v4.0.1">
        <title>Panel Admin</title>

        <!-- Bootstrap core CSS -->
        <link href="/assets/dist/css/bootstrap.css" rel="stylesheet">

        <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
            font-size: 3.5rem;
            }
        }
        </style>
        <!-- Custom styles for this template -->
        <link href="/assets/dashboard.css" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.css">
        <script   src="https://code.jquery.com/jquery-3.1.1.min.js"   integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="   crossorigin="anonymous"></script>

        {{-- quilljs.com/ --}}
        <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
    </head>
    <body>
        <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" href="/">Peralta & Asociados</a>
        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <input class="form-control form-control-dark w-100" type="text" placeholder="Buscar" aria-label="Search">
        <ul class="navbar-nav px-3">
            <li class="nav-item text-nowrap">
            <a class="nav-link" href="#">Salir</a>
            </li>
        </ul>
        </nav>
    
        <div class="container-fluid">
        <div class="row">
            <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
                <div class="sidebar-sticky pt-3">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active" href="/admin">
                            <span data-feather="file"></span>
                            Artículos <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/admin/new">
                            <span data-feather="plus"></span>
                            Cargar Artículo
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
    
            @yield('content')

        </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script>window.jQuery || document.write('<script src="/assets/js/vendor/jquery.slim.min.js"><\/script>')</script>
        <script src="/assets/dist/js/bootstrap.bundle.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
        {{-- <script src="/assets/dashboard.js"></script> --}}
        <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.js"></script>    

        {{-- quilljs.com/ --}}
        <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
        <script src="{{ asset('js/admin/app.js') }}"></script>
    </body>
</html>

resources/views/admin/new.blade.php
@extends('admin/layouts/layout')
@section('content')

<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Cargar Artículo</h1>
    </div>
    <section class="row">
        <div class="col-md-12">
            <form method="POST" id="articleForm" action="{{route('admin.store')}}" enctype="multipart/form-data">
                @csrf
                <div class="form-group col-lg-6">
                    <label for="title">Título:*</label>
                    <input @error('title') is-invalid @enderror required type="text" class="form-control" id="title" name="title">
                </div>
                <div class="form-group col-lg-6">
                    <label for="category">Categoría:*</label>
                    <select @error('category') is-invalid @enderror required class="form-control" id="category" name="category">
                        <option selected disabled>Seleccionar</option>
                        <option value="1">Violencia de Género</option>
                        <option value="2">Delitos contra la propiedad</option>
                        <option value="3">Delitos informáticos</option>
                        <option value="4">Derecho Penal Corporativo</option>
                    </select>
                </div>
                <div class="form-group col-md-10">
                    <label for="img">Imagen:* (Tamaño recomendado 600x600)</label>
                    <input @error('img') is-invalid @enderror type="file" id="img" name="img" required>
                </div>
                <div class="form-group col-md-10">
                    <label for="info">Texto:*</label>
                    {{-- <textarea @error('info') is-invalid @enderror required class="form-control" id="info" name="info" rows="16"></textarea> --}}
                </div>
                <input type="text" hidden name="info" id="info">
                <input type="text" hidden name="article" id="article">
                <input type="text" hidden name="squillContent" id="squillContent">
                <div id="editor" style="height: 450px; margin-bottom: 20px"></div>
                    
                </div>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif  
                <button class="btn btn-primary" type="submit" style="width:220px; margin-bottom:20px">Cargar</button>
            </form>
        </div>
    </section>
</main>
<script src="{{ asset('js/admin/new-article.js') }}" defer></script>
@endsection

resources/views/blog/index.blade.php
@extends('layouts/layout')
@section('content')

<section id="blog" class="section-ptb-80 bg-light-gold">
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-12">
				<div class="section-heading line center text-center">
					<h1 class="heading">Blog</h1>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<ul class="nav nav-pills mb-3 d-flex justify-content-center" id="pills-tab" role="tablist">
					<li class="nav-item" role="presentation">
					  <a class="nav-link active" id="pills-1-tab" data-toggle="pill" href="#pills-1" role="tab" aria-controls="pills-1" aria-selected="true">Violencia de Género</a>
					</li>
					<li class="nav-item" role="presentation">
					  <a class="nav-link" id="pills-2-tab" data-toggle="pill" href="#pills-2" role="tab" aria-controls="pills-2" aria-selected="false">Delitos contra la propiedad</a>
					</li>
					<li class="nav-item" role="presentation">
					  <a class="nav-link" id="pills-3-tab" data-toggle="pill" href="#pills-3" role="tab" aria-controls="pills-3" aria-selected="false">Delitos Informáticos</a>
					</li>
					<li class="nav-item" role="presentation">
						<a class="nav-link" id="pills-4-tab" data-toggle="pill" href="#pills-4" role="tab" aria-controls="pills-4" aria-selected="false">Derecho Penal Corporativo</a>
					  </li>
				  </ul>
			</div>
		</div>

		<div class="tab-content" id="pills-tabContent">
			<div class="tab-pane fade show active" id="pills-1" role="tabpanel" aria-labelledby="pills-1-tab">
				<div class="container">
					<div class="row justify-content-center">
						<div class="col-12">
							<div class="section-heading line center text-center">
								<h1 class="heading">Lo último</h1>
							</div>
						</div>
					</div>
					<div class="row mt-50">
						@foreach ($blogs as $blog)
							@if ($blog->category == 1)
								<div class="col-lg-4 col-md-4 mb-50">
									<div class="blog-post xs-mb-50">
										<div class="entry-image clearfix">
											<img class="img-fluid" src="/storage/blog/{{$blog->img}}" alt="{{$blog->title}}">
										</div>
										<div class="blog-detail">
											<div class="entry-title mb-10">
												<a href="{{route('blog.show', $blog->id)}}">{{$blog->title}}</a>
											</div>
											<div class="entry-meta mb-10">
												<ul>
													<li><a href="{{route('blog.show', $blog->id)}}"><i class="fa fa-calendar-o"></i> {{$blog->updated_at->diffForHumans()}}</a></li>
												</ul>
											</div>
											<div class="entry-content">
												<p>{{ substr($blog->info, 0,  20) }}...</p>
											</div>
											<div class="entry-share clearfix">
												<div class="entry-button">
													<a class="cs-button arrow" href="{{route('blog.show', $blog->id)}}">Ver más<i class="fa fa-angle-right" aria-hidden="true"></i></a>
												</div>
												{{-- <div class="social list-style-none float-right">
													<strong>Share : </strong>
													<ul>
														<li>
															<a href="{{route('blog.show', $blog->id)}}"> <i class="fa fa-facebook"></i> </a>
														</li>
														<li>
															<a href="#"> <i class="fa fa-twitter"></i> </a>
														</li>
													</ul>
												</div> --}}
											</div>
										</div>
									</div>
								</div>
							@endif
						@endforeach
					</div>
				</div>
			</div>
			<div class="tab-pane fade" id="pills-2" role="tabpanel" aria-labelledby="pills-2-tab">
				<div class="container">
					<div class="row justify-content-center">
						<div class="col-12">
							<div class="section-heading line center text-center">
								<h1 class="heading">Lo último</h1>
							</div>
						</div>
					</div>
					<div class="row mt-50">
						@foreach ($blogs as $blog)
							@if ($blog->category == 2)
								<div class="col-lg-4 col-md-4 mb-50">
									<div class="blog-post xs-mb-50">
										<div class="entry-image clearfix">
											<img class="img-fluid" style="height: 350px; width:350px;" src="/storage/blog/{{$blog->img}}" alt="{{$blog->title}}">
										</div>
										<div class="blog-detail">
											<div class="entry-title mb-10">
												<a href="{{route('blog.show', $blog->id)}}">{{$blog->title}}</a>
											</div>
											<div class="entry-meta mb-10">
												<ul>
													<li><a href="{{route('blog.show', $blog->id)}}"><i class="fa fa-calendar-o"></i> {{$blog->updated_at->diffForHumans()}}</a></li>
												</ul>
											</div>
											<div class="entry-content">
												<p>{{ substr($blog->info, 0,  20) }}...</p>
											</div>
											<div class="entry-share clearfix">
												<div class="entry-button">
													<a class="cs-button arrow" href="{{route('blog.show', $blog->id)}}">Ver más<i class="fa fa-angle-right" aria-hidden="true"></i></a>
												</div>
												{{-- <div class="social list-style-none float-right">
													<strong>Share : </strong>
													<ul>
														<li>
															<a href="{{route('blog.show', $blog->id)}}"> <i class="fa fa-facebook"></i> </a>
														</li>
														<li>
															<a href="#"> <i class="fa fa-twitter"></i> </a>
														</li>
													</ul>
												</div> --}}
											</div>
										</div>
									</div>
								</div>
							@endif
						@endforeach
					</div>
				</div>
			</div>
			<div class="tab-pane fade" id="pills-3" role="tabpanel" aria-labelledby="pills-3-tab">
				<div class="container">
					<div class="row justify-content-center">
						<div class="col-12">
							<div class="section-heading line center text-center">
								<h1 class="heading">Lo último</h1>
							</div>
						</div>
					</div>
					<div class="row mt-50">
						@foreach ($blogs as $blog)
							@if ($blog->category == 3)
								<div class="col-lg-4 col-md-4 mb-50">
									<div class="blog-post xs-mb-50">
										<div class="entry-image clearfix">
											<img class="img-fluid" style="height: 350px; width:350px;" src="/storage/blog/{{$blog->img}}" alt="{{$blog->title}}">
										</div>
										<div class="blog-detail">
											<div class="entry-title mb-10">
												<a href="{{route('blog.show', $blog->id)}}">{{$blog->title}}</a>
											</div>
											<div class="entry-meta mb-10">
												<ul>
													<li><a href="{{route('blog.show', $blog->id)}}"><i class="fa fa-calendar-o"></i> {{$blog->updated_at->diffForHumans()}}</a></li>
												</ul>
											</div>
											<div class="entry-content">
												<p>{{ substr($blog->info, 0,  20) }}...</p>
											</div>
											<div class="entry-share clearfix">
												<div class="entry-button">
													<a class="cs-button arrow" href="{{route('blog.show', $blog->id)}}">Ver más<i class="fa fa-angle-right" aria-hidden="true"></i></a>
												</div>
												{{-- <div class="social list-style-none float-right">
													<strong>Share : </strong>
													<ul>
														<li>
															<a href="{{route('blog.show', $blog->id)}}"> <i class="fa fa-facebook"></i> </a>
														</li>
														<li>
															<a href="#"> <i class="fa fa-twitter"></i> </a>
														</li>
													</ul>
												</div> --}}
											</div>
										</div>
									</div>
								</div>
							@endif
						@endforeach
					</div>
				</div>
			</div>
			<div class="tab-pane fade" id="pills-4" role="tabpanel" aria-labelledby="pills-4-tab">
				<div class="container">
					<div class="row justify-content-center">
						<div class="col-12">
							<div class="section-heading line center text-center">
								<h1 class="heading">Lo último</h1>
							</div>
						</div>
					</div>
					<div class="row mt-50">
						@foreach ($blogs as $blog)
							@if ($blog->category == 4)
								<div class="col-lg-4 col-md-4 mb-50">
									<div class="blog-post xs-mb-50">
										<div class="entry-image clearfix">
											<img class="img-fluid" src="/storage/blog/{{$blog->img}}" alt="{{$blog->title}}">
										</div>
										<div class="blog-detail">
											<div class="entry-title mb-10">
												<a href="{{route('blog.show', $blog->id)}}">{{$blog->title}}</a>
											</div>
											<div class="entry-meta mb-10">
												<ul>
													<li><a href="{{route('blog.show', $blog->id)}}"><i class="fa fa-calendar-o"></i> {{$blog->updated_at->diffForHumans()}}</a></li>
												</ul>
											</div>
											<div class="entry-content">
												<p>{{ substr($blog->info, 0,  20) }}...</p>
											</div>
											<div class="entry-share clearfix">
												<div class="entry-button">
													<a class="cs-button arrow" href="{{route('blog.show', $blog->id)}}">Ver más<i class="fa fa-angle-right" aria-hidden="true"></i></a>
												</div>
												{{-- <div class="social list-style-none float-right">
													<strong>Share : </strong>
													<ul>
														<li>
															<a href="{{route('blog.show', $blog->id)}}"> <i class="fa fa-facebook"></i> </a>
														</li>
														<li>
															<a href="#"> <i class="fa fa-twitter"></i> </a>
														</li>
													</ul>
												</div> --}}
											</div>
										</div>
									</div>
								</div>
							@endif
						@endforeach
					</div>
				</div>
			</div>
		  </div>
	</div>
</section>

@include('partials/contact')
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection